### ISSUE TITLE
Missing Entries in Menu.Root after 0.51.01 upgrade

### ISSUE THREAD

**Issue by Hedydd** [ChromisPos/ChromisPOS#11]
I lost these entries after the upgrade and had to re-enter them manually, there is no reason for them not to be added to the standard menus for everyone but even if not, the upgrade should not over-write existing entries.

Under : submenu.addTitle("Menu.StockManagement.Reports");

submenu.addPanel("/uk/chromis/images/reports.png", "Menu.InventoryReOrder", "/uk/chromis/reports/inventoryreorder.bs");

Under: submenu.addTitle("Menu.StockManagement.Edit");

submenu.addPanel("/uk/chromis/images/stockmaint.png", "Menu.ProductPacks", "uk.chromis.pos.inventory.ProductPacksPanel");

**Comment by ChromisPos** [comment]
Hi John

I will check out what happening, I thought I merged the changes, but it looks like something went wrong, I will add to the next release of the code. 

John

**Comment by Hedydd** [comment]
When you commit a fix for this, the issue can be tagged and closed during the commit process.

**Comment by ChromisPos** [comment]
Hi John

Was about to release new version with your productPacks in it, but I have had to remove for the time being, It does not work with Derby, I think it is because of the FK (it does not appear to create it properly). So we will need to investigate it before it can go into the main code.

John

**Comment by ChromisPos** [comment]
Hi John

Was about to release new version with your productPacks in it, but I have had to remove for the time being, It does not work with Derby, I think it is because of the FK (it does not appear to create it properly). So we will need to investigate it before it can go into the main code.

John
