### ISSUE TITLE
linux installation problem: correct version of JRE is not detected

### ISSUE THREAD

**Issue by hyOzd** [ChromisPos/ChromisPOS#12]
I'm trying to install ChromisPOS 0.51 linux amd64 version on Linux Mint and getting an error dialog that says "Correct version of JRE is not detected, Please install Java 1.8 etc.."

Then it opens a web page to oracle java. Do I really need to install the oracle version of java? Doesn't ChromisPOS work with openjdk?

I had the same error message when I tried unicentapos but for some reason it continued with installation fine : ) Then I was able to start uncentapos and it worked -seemingly- fine with openjdk-7. But I cannot install chromispos at all, maybe if I was able to install, it would work as well?

I've also tried installing openjdk-8 (which I believe provides java 1.8) and it didn't work.

**Comment by cubanflyer** [comment]
Hi 

Can you post you question on the Chromis forum, I will look into the openJDK issue when I get the chance.

John l

**Comment by cubanflyer** [comment]
I have updated the installer package which should allow OpenJDk, if you can test and let me know.

Thanks
John l

**Comment by hyOzd** [comment]
Now it works. Thanks!

But there is a slight problem. Although I was able to install by selecting openjdk-7, application didn't launch with it. I had to install openjdk-8 and change my default java version using `update-alternatives` command. Then application launched fine. I think you should warn the user during install that chromispos requires openjdk-8 (java 1.8) version.

**Comment by cubanflyer** [comment]
Thanks. It should not allow anything less than 1.8 in the installer I will need to check it again.

It states 1.8 for Oracle, in the readme will be updated when the next official release is put out. to include OpenJDK 1.8

John l
