### ISSUE TITLE
Derby Database and booleans

### ISSUE THREAD

**Issue by Hedydd** [ChromisPos/ChromisPOS#14]
I was going to look at problems with product packs and using Derby database and got bogged down because there are other more serious issues with using Derby.

Derby database DOES support the boolean data type so why is this line at the top of createdb.xml and updatedb.xml?

    <property name="boolean.type" value="smallint" dbms="derby"/>

This means you cannot use true and false as values for any field defined as boolean.type

I tried changing to;
    <property name="boolean.type" value="boolean" dbms="derby"/>

but that causes many more issues in the files because values are often set to 0 or 1.

This is a bigger job than I have time for and until it is fixed I cannot create a derby database to test product packs with.

**Comment by cubanflyer** [comment]
I will look at changing the original scripts used small int, so I converted those over.

john

**Comment by cubanflyer** [comment]
Hi John

I have modified the latest liquibase build to allow larger blobs and read as  blob for a resource, which it does not do by default.

I have almost complete the re write of the scripts, and started testing, it looks like it may have resolved the FK issue, I will keep you posted.

John
