### ISSUE TITLE
Creation of a new Database does not work due to use of "valueBlobResource" attribute

### ISSUE THREAD

**Issue by jan-moxter** [ChromisPos/ChromisPOS#20]
On Installation of a new database using Postgres, the installation fails due to the use of the "valueBlobResource" attribute in createdb.xml instead of "valueBlobFile" as defined in the related xsd

**Comment by jan-moxter** [comment]
If interested pull request can be provided

**Comment by jan-moxter** [comment]
I just realised that using the installer for windows with Postgres doe not fail at this. but Using the source code on a linux does fail

**Comment by ChromisPos** [comment]
This is a customised Liquibase, as by default it does not support pulling resources from jar file. There is also a size limitation.
