### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Webgace** [ChromisPos/ChromisPOS#26]
I just found this priceless application and not sure if this is place to ask for help. If not my sincerest apology.
I'm not a programmer and would like to know how to change the name Chromis V0.53.1, that is displayed on the top left side of the window.

Thanks and best regards
Jomes

**Comment by jan-moxter** [comment]
Hallo
ask here:
http://sourceforge.net/p/chromispos/discussion/help/

**Comment by Webgace** [comment]
thanks
