### ISSUE TITLE
conversion routines need to remove PosApps reference from ticket.close

### ISSUE THREAD

**Issue by Hedydd** [ChromisPos/ChromisPOS#3]
In my resources ticket.close script there was a reference to and initialisation of a PosApps object, I assume this is an unused remnant of unipos.

PosApps no longer exists in Chromis so either the object library needs adding to the project or the reference in the resources table needs removing by the conversion routines.

**Comment by cubanflyer** [comment]
This should have been removed, it is a call to a Unicenta external receipt app.
